"""create landlord_table

Revision ID: 005c63592d01
Revises: 
Create Date: 2024-12-10 10:23:54.230176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005c63592d01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landlords_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('associated_llcs', sa.String(), nullable=False),
    sa.Column('violations', sa.String(), nullable=True),
    sa.Column('currently_in_litigation', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('landlords_table')
    # ### end Alembic commands ###
