"""one to many established

Revision ID: 579c8b7d1c14
Revises: 005c63592d01
Create Date: 2024-12-10 14:24:19.239717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579c8b7d1c14'
down_revision = '005c63592d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violations_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currently_in_litigation', sa.Boolean(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('Landlord_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Landlord_id'], ['landlords_table.id'], name=op.f('fk_violations_table_Landlord_id_landlords_table')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('landlords_table', schema=None) as batch_op:
        batch_op.drop_column('violations')
        batch_op.drop_column('currently_in_litigation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlords_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currently_in_litigation', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('violations', sa.VARCHAR(), nullable=True))

    op.drop_table('violations_table')
    # ### end Alembic commands ###
